<?php
// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Register the block visibility meta field.
 * NOTE: We register the field as a string here because the block attribute 
 * is a boolean in JS, but when saved to post meta, WP sometimes converts it 
 * to a string representation ('true'/'false' or '1'/'0').
 */
function aaee_register_block_visibility_meta() {
    register_post_meta( '', 'aaee_live_hide', array(
        'show_in_rest' => true,
        'single'       => true,
        // The type must be handled carefully. Since your JS uses boolean, 
        // we'll use string to allow 'true'/'false' storage via the REST API.
        'type'         => 'string', 
        'default'      => 'false',
        'auth_callback' => function() {
            return current_user_can( 'edit_posts' );
        }
    ) );
}
add_action( 'init', 'aaee_register_block_visibility_meta' );


/**
 * Enqueue the required assets for the Gutenberg Editor.
 */
function aaee_enqueue_visibility_assets() {
    // --- CORRECTED PATHING TO 'build/' ---
    $asset_dir_url = plugin_dir_url( __FILE__ ) . 'build/';
    $asset_dir_path = plugin_dir_path( __FILE__ ) . 'build/';
    
    // Check if the script and its generated asset file exist before enqueuing
    if ( ! file_exists( $asset_dir_path . 'index.js' ) || ! file_exists( $asset_dir_path . 'index.asset.php' ) ) {
        return;
    }
    // -------------------------

    // Dependencies + version are generated by wp-scripts at build time.
    $asset = include $asset_dir_path . 'index.asset.php';

    // 1. Enqueue the JavaScript (React component for the sidebar control)
    wp_enqueue_script(
        'aaee-visibility-editor-script',
        $asset_dir_url . 'index.js',
        $asset['dependencies'],
        $asset['version'],
        true // Load in footer
    );

    // 2. CSS: the sidebar UI uses core components, so no stylesheet is needed.
    // If one is added later (build/index.css), only enqueue it when it exists.
    // Styles that target blocks in the canvas should use 'enqueue_block_assets'.
    if ( file_exists( $asset_dir_path . 'index.css' ) ) {
        wp_enqueue_style(
            'aaee-visibility-editor-style',
            $asset_dir_url . 'index.css',
            array( 'wp-components' ),
            $asset['version']
        );
    }
}
// Hook into the Gutenberg editor assets action
add_action( 'enqueue_block_editor_assets', 'aaee_enqueue_visibility_assets' );


/**
 * Register the visibility attributes on the server for every block.
 * Without this, dynamic blocks previewed in the editor (ServerSideRender)
 * reject the unknown attributes with an "Invalid parameter(s): attributes" error.
 */
function aaee_register_visibility_block_attributes( $args ) {
    if ( ! isset( $args['attributes'] ) || ! is_array( $args['attributes'] ) ) {
        $args['attributes'] = array();
    }

    $args['attributes']['aaeeLiveHide'] = array(
        'type'    => 'boolean',
        'default' => false,
    );
    $args['attributes']['aaeeHideOn'] = array(
        'type'    => 'string',
        'default' => '',
    );

    return $args;
}
add_filter( 'register_block_type_args', 'aaee_register_visibility_block_attributes' );


/**
 * Work out where a block should be hidden: '', 'mobile', 'desktop' or 'all'.
 */
function aaee_get_block_hide_on( $attrs ) {
    $hide_on = isset( $attrs['aaeeHideOn'] ) ? $attrs['aaeeHideOn'] : '';

    if ( in_array( $hide_on, array( 'mobile', 'desktop', 'all' ), true ) ) {
        return $hide_on;
    }

    // Legacy toggle: a PHP boolean or a string 'true'/'false' or 1/0 from the database/REST API.
    $legacy = isset( $attrs['aaeeLiveHide'] ) ? $attrs['aaeeLiveHide'] : false;
    if ( $legacy === true || $legacy === 'true' || $legacy === 1 || $legacy === '1' ) {
        return 'all';
    }

    return '';
}


/**
 * Print the responsive hide rules. Only enqueued on pages that use them.
 */
function aaee_enqueue_visibility_frontend_style() {
    if ( wp_style_is( 'aaee-visibility-frontend', 'enqueued' ) ) {
        return;
    }

    // Screens narrower than this are "mobile". Filterable per site.
    $breakpoint = (int) apply_filters( 'aaee_visibility_mobile_breakpoint', 768 );

    $css = sprintf(
        '@media (max-width: %1$dpx){.aaee-hide-mobile{display:none !important;}}' .
        '@media (min-width: %2$dpx){.aaee-hide-desktop{display:none !important;}}',
        $breakpoint - 1,
        $breakpoint
    );

    wp_register_style( 'aaee-visibility-frontend', false );
    wp_add_inline_style( 'aaee-visibility-frontend', $css );
    wp_enqueue_style( 'aaee-visibility-frontend' );
}


/**
 * Apply the visibility filter on the front-end.
 * 'all' removes the block from the HTML; 'mobile'/'desktop' add a CSS class
 * so the result is the same for every visitor (safe with page caching).
 */
function aaee_render_block_visibility_filter( $block_content, $block ) {
    // Only apply the filter to actual block rendering on the frontend (not the editor or its REST previews).
    if ( is_admin() || ( defined( 'REST_REQUEST' ) && REST_REQUEST ) || empty( $block['attrs'] ) ) {
        return $block_content;
    }

    $hide_on = aaee_get_block_hide_on( $block['attrs'] );

    if ( $hide_on === '' ) {
        return $block_content; // Show the block.
    }

    if ( $hide_on === 'all' ) {
        return ''; // Return an empty string (hide the block).
    }

    // Add the class to the block's outer HTML element.
    $processor = new WP_HTML_Tag_Processor( $block_content );
    if ( ! $processor->next_tag() ) {
        return $block_content; // No HTML wrapper to target.
    }
    $processor->add_class( 'aaee-hide-' . $hide_on );

    aaee_enqueue_visibility_frontend_style();

    return $processor->get_updated_html();
}
add_filter( 'render_block', 'aaee_render_block_visibility_filter', 10, 2 );